#!/bin/sh
set -e

USER_DB_NAME="${USER_DB_NAME:-payflow_user}"
WALLET_DB_NAME="${WALLET_DB_NAME:-payflow_wallet}"
TRANSFER_DB_NAME="${TRANSFER_DB_NAME:-payflow_transfer}"
LEDGER_DB_NAME="${LEDGER_DB_NAME:-payflow_ledger}"
SETTLEMENT_DB_NAME="${SETTLEMENT_DB_NAME:-payflow_settlement}"
MYSQL_USER="${MYSQL_USER:-payflow}"

mysql -uroot -p"${MYSQL_ROOT_PASSWORD}" <<EOSQL
CREATE DATABASE IF NOT EXISTS \`${USER_DB_NAME}\`
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;

CREATE DATABASE IF NOT EXISTS \`${WALLET_DB_NAME}\`
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;

CREATE DATABASE IF NOT EXISTS \`${TRANSFER_DB_NAME}\`
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;

CREATE DATABASE IF NOT EXISTS \`${LEDGER_DB_NAME}\`
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;

CREATE DATABASE IF NOT EXISTS \`${SETTLEMENT_DB_NAME}\`
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;

GRANT ALL PRIVILEGES ON \`${USER_DB_NAME}\`.* TO '${MYSQL_USER}'@'%';
GRANT ALL PRIVILEGES ON \`${WALLET_DB_NAME}\`.* TO '${MYSQL_USER}'@'%';
GRANT ALL PRIVILEGES ON \`${TRANSFER_DB_NAME}\`.* TO '${MYSQL_USER}'@'%';
GRANT ALL PRIVILEGES ON \`${LEDGER_DB_NAME}\`.* TO '${MYSQL_USER}'@'%';
GRANT ALL PRIVILEGES ON \`${SETTLEMENT_DB_NAME}\`.* TO '${MYSQL_USER}'@'%';
FLUSH PRIVILEGES;
EOSQL
